### ISSUE TITLE
Change default logging settings

### ISSUE THREAD

**Issue by Lemonymous** [itb-community/ITB-ModLoader#135]
Sometimes someone comes a long and needs help with something going wrong with the mod loader or a mod.
To help the individual, we must then first go through a series of settings changes to the mod loader, in order to be able to make it print out logs to file.

## Proposed changes:
- Add an option to clear `modloader.log` on ITB startup and set this to default.
- Set log to console and file as default.

**Comment by kartoFlane** [comment]
Sounds good to me. I guess we might also want to make the caller information setting no longer default?

**Comment by KnightMiner** [comment]
I believe the only change we need to replace the log instead of appending is on this line: https://github.com/itb-community/ITB-ModLoader/blob/master/scripts/mod_loader/logger_basic.lua#L72

Replace `"a+"` with `"w+"` configurably.

**Comment by Lemonymous** [comment]
Fixed in eb24f60
