### ISSUE TITLE
GetText for AE units

### ISSUE THREAD

**Issue by Lemonymous** [itb-community/ITB-ModLoader#136]
Using `GetText` for any pre-AE unit id's at mod init will correctly return the unit name.
Using `GetText` for any AE unit id's in the console will correctly return the unit name.

However:
Using `GetText` for any AE unit id's at mod init will **incorrectly return the unit id**, instead of its name.

**Edit:** Actually it might only be for Psions. `GetText("Jelly_Spider1")` was my test case. Correct return name should be "Arachnid Psion".

**Comment by KnightMiner** [comment]
I suspect preinit just won't work for reading texts. I do not believe game settings have loaded yet, meaning the language is not yet selected. The text you are getting is being pulled from the old text global tables which are used as fallbacks right now (guess some vanilla texts never got added to the tables)

I would suggest just waiting to get texts until load, means you can properly update if the language changes.

**Comment by Lemonymous** [comment]
Would an `onLanguageLoading` and and `onLanguageLoaded` event be in order?

Both would trigger when the game has initialized and the language file has been loaded, and again each time the language is changes in settings.

We could then use `onLanguageLoading` to set texts the current mod will be using, and `onLanguageLoaded` to get texts from the new language change. Might make it possible to localize mods.
