### ISSUE TITLE
Unfair ribbons are larger than regular ribbons, causing a visible border

### ISSUE THREAD

**Issue by KnightMiner** [itb-community/ITB-ModLoader#143]
![image](https://user-images.githubusercontent.com/12155288/182526243-e60900b4-65ad-43df-af85-fde84cabe7b3.png)

![image](https://user-images.githubusercontent.com/12155288/182526337-5d23885d-de8d-4de7-93e3-b8a0562343f2.png)

Unfair mode ribbons are larger, so the mod loader ribbons don't fully overlap it. Might need to draw a background or add a border to the ribbons

Background in  the squad selector would also help with #138

**Comment by Lemonymous** [comment]
Fixed in 9bb9f5d087181c8b4238caaf8dfb66428ebc4c45
