### ISSUE TITLE
Game wont launch getting a nil error message

### ISSUE THREAD

**Issue by TruAle** [itb-community/ITB-ModLoader#148]
When I click launch game the "LOADING" screen appears for a second and then the window in the attached screenshot appears. Ive tried to check online for a solution and tried a few that I found without success. What could be causing this?
[https://imgur.com/a/XDQ849O](url)

**Comment by KnightMiner** [comment]
Use modloader 2.7.1 on ITB advanced editioj, not 2.6.4

**Comment by KnightMiner** [comment]
Going to close for lack of response. This issue is typically caused by being on an old modloader so I will assume that is the issue
