### ISSUE TITLE
New Advanced Edition pilot abilities show "NOT FOUND" when getting the "Info Overlay" in game. 

### ISSUE THREAD

**Issue by NamesAreHard6600** [itb-community/ITB-ModLoader#151]
When holding left ctrl (default) over pawns, you can reveal an info panel over them, and when doing so on mechs, it provides their status effects and pilot abilities. The new AE pilot abilities add a status effect to mechs when active, but their tips are listed as NOT FOUND (see photos)
![Screenshot 2022-08-13 142038](https://user-images.githubusercontent.com/109428297/184511622-e17b0e96-f6bd-4ddb-ad2e-59094f62b7c0.png)![Screenshot 2022-08-13 142809](https://user-images.githubusercontent.com/109428297/184511623-94aa0c9f-0663-42ea-ac8c-049f0ba49897.png)![Screenshot 2022-08-13 143731](https://user-images.githubusercontent.com/109428297/184511625-11b269f2-6e07-4462-9ce7-f1a3b5a2f058.png)

Versions: 
Modloader: 2.7.1
Game Version: 1.2.76b (07-29-2022)

This error occurs when no mods are installed (mods folder is empty) but does not occur when the modloader is uninstalled. @ me, NamesAreHard (no numbers) on the Into the Breach discord for more info, I make no promises for anything on github because I'm very new to it.

**Comment by KnightMiner** [comment]
![image](https://user-images.githubusercontent.com/12155288/185782002-2319058d-5e11-4d87-8d6e-6fc346816894.png)
The beta 1.2.78 patch is nice, every pilot gets conservative and technician so its easy to test this
