### ISSUE TITLE
Crash starting the game

### ISSUE THREAD

**Issue by AndreyCamper** [itb-community/ITB-ModLoader#161]
[https://imgur.com/a/dskZjXR](url)

**Comment by KnightMiner** [comment]
Need more information than that to debug this issue. Please upload your `modloader.log` file from the game directory. Its the same folder where you installed the modloader

**Comment by AndreyCamper** [comment]
I have no modloader.log file in the game directory. [https://imgur.com/xIojQof](url)

**Comment by AndreyCamper** [comment]
P.S. i also tried 2.7.1 and super old 2.6.4. They have the same error. (sometimes individual numbers of individual errors differ from the previous ones).

**Comment by KnightMiner** [comment]
Please join the discord (linked on the readme) and use the `modding-support` channel to debug this more, we can return here if we confirmed its a modloader bug.

**Comment by AndreyCamper** [comment]
Fixed: RivaTunerStatistikServer from Afterburner crashes the modloader.
First launch with RTSS off, second launch with RTSS on: The game works.
