### ISSUE TITLE
Load game events needs looking at

### ISSUE THREAD

**Issue by Lemonymous** [itb-community/ITB-ModLoader#162]
`modApi.events.onPreLoadGame` and `modApi.events.onPostLoadGame` are dispatched when there is no Board, and the current mission might also not be available.

This makes it difficult to use them for updating the Board when loading the game.

I have not delved too deep into it, so more investigation would be in order.

**Comment by KnightMiner** [comment]
Would it be possible to hook into `SetBoard` and make an `onBoardAvailable` event? You could listen to both events to determine when the game is loaded and the board is available via a simple "state machine"

**Comment by Lemonymous** [comment]
Not a bad idea in principle. I do have some questions about how an onBoardAvailable event would be set up in order to be useful though. In my current tests now, while hovering a tipimage, the event will fire constantly changing `Board` from the mission board and the tipimage board.

**Comment by Lemonymous** [comment]
After some work on an `onGameStateChanged` event (Finished, but requires nuking an old version of Easy Edit before it can be commited), I realized that the event `onMissionChanged` serves very well for my particular use case (updating the Board after loading the game).

i.e.
```lua
modApi.events.onMissionCHanged:subscribe(function(mission, oldMission)
    if mission then
        -- update board
    end
end)
```

I am not sure when the load game hooks are best used, but they should probably remain the same in order to not cause any unforeseen consequences to code using those events.
