### ISSUE TITLE
Vanilla squads show modded victories

### ISSUE THREAD

**Issue by KnightMiner** [itb-community/ITB-ModLoader#170]
Since modded squads are added by replacing vanilla squads, it is possible to earn a vanilla ribbon with a modded squad. Similar to #169, there may not be anything we can do to prevent earning them, but we could at least hide the false victories.

## Approach 1: Statistics

* On profile load, scan the statistics to find the true best victory and displayed victory for each squad. Can do so by iterating all previous runs.
* If it was a vanilla squad and has the proper mechs, track that as a true best
* If it was a modded squad (improper mechs), track that as a false best
* At the end, should have true and false bests for each vanilla squad for each of the 3 lengths. If the false best is greater than the true best, save an override
* On loading the hangar with a vanilla squad, if there are any overrides display ribbons over then for the override value, use the same logic as modded squad ribbons.
* On victory,
    * If the victory is a vanilla squad, check if we can remove the override
    * If the victory is a modded squad and is greater than our previous victory, add an override for the old value.

## Approach 2: saved mod content

This approach takes just the last step from approach 1, simply tracking if we have any falsely earned victories.

* When starting the final island, store the best ribbon for that length into the modded save data
* When finishing the final island:
    * If playing a modded squad and the victory is greater than the previous, add an override for the old value.
    * If playing a vanilla squad and the victory makes the override not needed, remove it
* On loading the hangar with a vanilla squad, if there are any overrides display ribbons over then for the override value, use the same logic as modded squad ribbons.

**Comment by Lemonymous** [comment]
Fixed in 9bb9f5d087181c8b4238caaf8dfb66428ebc4c45
