### ISSUE TITLE
easyEdit: Add a "copy list" button

### ISSUE THREAD

**Issue by tos-x** [itb-community/ITB-ModLoader#183]
Allow new lists to be created based off of an existing list. It is currently very tedious to make a slightly expended version of a list without messing with the default lists, which users may not wish to do. Implementation ideas:

1. Add a "Copy" button below "Create new list", which allows selection of an existing list before picking a name; would require a new selection UI?
2. Add a "Copy" icon next to each list's "Reset" icon; user would click the copy icon for a specific list, and it would then place the copy and prompt for a name just like with the "Create new list" button.

**Comment by NamesAreHard6600** [comment]
I can probably work on this as a larger project once we get the important stuff done and released.
