### ISSUE TITLE
2.8.3 and 2.8.2 erase all AE map files on launch

### ISSUE THREAD

**Issue by tos-x** [itb-community/ITB-ModLoader#184]
Looks like modloader 2.8.3 (and 2.8.2; I didn't go back farther) removes all AE maps when you launch the modded game. It appears to happen during the waiting period before the loading bar begins (what used to be the command window popup period). When trying to load a specific mission with an AE map like mission Mission_Disposal disposalAE1 it gives a different map (no error message); trying to load disposalAE1 in mapeditor says it can't find it. In my unmodded game I can see the AE map files and get them in-game just fine.

**Comment by KnightMiner** [comment]
Seems the issue goes back farther to 2.7 and likely any modloader version that supports AE.

**Comment by KnightMiner** [comment]
Merge #185 which addresses this, will leave this issue open until next release.
