### ISSUE TITLE
Fix SpaceDamage:HasMetadata()

### ISSUE THREAD

**Issue by tos-x** [itb-community/ITB-ModLoader#197]
In [skills.lua](https://github.com/itb-community/ITB-ModLoader/blob/master/scripts/mod_loader/modapi/skills.lua), `SpaceDamage:HasMetadata()` should check for "return " with a space, to be more robust.

e.g.
`return modApi:stringStartsWith(self.sScript, "return ")`
...not
`return modApi:stringStartsWith(self.sScript, "return")`

**Comment by KnightMiner** [comment]
Is this causing any issues? Unless a global variable starts with the word return I cannot see this detecting a false positive.

**Comment by Lemonymous** [comment]
A script calling a global function starting with "return" could yield a false positive.

The mod loader function that adds metadata always starts with "return ", so this change should still always correctly identify a SpaceDamage instance with metadata stored in its sScript.

**Comment by Lemonymous** [comment]
This will become a non-issue once #198 has been fully resolved
