### ISSUE TITLE
Metadata in SpaceDamage objects can pose additional challenges

### ISSUE THREAD

**Issue by Lemonymous** [itb-community/ITB-ModLoader#198]
### Description
SpaceDamage object's metadata is a fairly obscure thing, that is not used by many (or any?) current mod. It is not a well known thing, and could cause bugs if not handled correctly.

There exists situations where one might want to extend the script of a SpaceDamage instance in a SkillEffect that was not initially created by your mod.

In this situation, this is the order of events:
- A SkillEffect object is created
- A SpaceDamage object is created
- The SpaceDamage object is modified in for example a weapon's GetSkillEffect
- The SpaceDamage object is passed to a SkillEffect function (for example AddProjectile)
- If using `AddProjectile`, `AddQueuedProjectile`, `AddArtillery` or `AddQueuedArtillery`, the mod loader will add some metadata:
    - If the SpaceDamage object's sScript is empty, that metadata will be stored in the object's own sScript.
    - If the SpaceDamage object's sScript is not empty, that metadata will be stored in another SpaceDamage object added to the SkillEffect object.
- SkillBuild events from other mods can now have their turn in modifying the SkillEffect object and its SpaceDamage objects.

The metadata sScript starts with "return ". This causes back-concatenation to the SpaceDamage object's sScript to fail.

### Potential solutions
- The metadata could always be added to its separate SpaceDamage object.
- Function(s) could be added to handle concatenating strings to SpaceDamage objects' sScript correctly. Downside: The max length of an sScript is finite, so the metadata would take some available script space.
- Function(s) could be added to free up the metadata script, and move the metadata to a separate SpaceDamage instance.
- Other?

**Comment by KnightMiner** [comment]
Separate space damage object breaks some achievements, so that route is not worth going down.

If you need to add a script to metadata, your best bet is really moving the metadata to another space damage object, or just inserting a script after the metadata. Best bet unless we ditch metadata that is

**Comment by Lemonymous** [comment]
I see. I do not personally need this, but it has been posed as a question to me. And I do not have any function to redirect them to, nor know of any easy way around the issue other than just overwriting the sScript. Is that a valid solution?

What about rethinking how the metadata is connected to the SpaceDamage. In theory, you wouldn't have to store the data directly in the script. All you need is to store some unique id that can be used to fetch the data from another table.

So instead of storing the data as a table in script form, how about declaring a local variable in the script (or finding another SpaceDamage property that is inconsequential to the SpaceDamage type in question). The name of the local variable could be the unique id.

```lua
spaceDamage.sScript = "local meta001 "
-- or
spaceDamage.someInconsequentialProperty = 1
```

Challenges this solution could pose:
- The name of the local variable should be fairly unique to avoid false positives from real scripts.
- A data table could continue to increase in size indefinitely, unless some way is found to know the end of the lifetime of the SpaceDamage instance, to free up the id.
- Other?

Another solution could be to identify the metadata in the SpaceDamage objects with memedit, and making functions to get them.

**Comment by KnightMiner** [comment]
you cannot set another property, space damage is a userdata object which means any invalid keys are discarded. So unless you know of an existing unused property that stores the data there is not a lot that can be done.

It is an interesting idea to use a local as a key like that, though I am concerned about added complexity in both saving and processing metadata. Most notably as there is no where else we can store the data in a space damage object, thus we would have to store it externally, the more "gobally" it is stored, the more difficult it becomes to ensure it stays in sync (e.g. we can store it in the skill effect, but copying the space damage may happen without copying the skill effect). I do not much like the idea of making this a global table that gets filled every time there is metadata either, as you would be creating 5+ new instances every time a skill effect is invoked so that table will very quickly explode in size.

Getting that data directly via memedit instead of storing it ourselfs would probably be the best solution.

**Comment by Lemonymous** [comment]
I understand, and I am inclined to agree.

I have explored finding memedit values in the SpaceDamage objects, and I am seeing some success. Finding the source X and Y was fairly easy, so it should be possible to find other values as well. I am able to both fetch and change the values with memedit functions.

However, I am uncertain of how I can add functions to the SpaceDamage objects.
I am also uncertain of all the values I should be hunting for.

From what I can see in the mod loader's `modApi/skills.lua`, it looks like I am hunting for the following properties:
source X and Y - found
projectile/artillery art - found, and they both use the same address
whether the SpaceDamage is an artillery, projectile, or none - no attempt at finding this yet

Any idea how I can add functions to SpaceDamage objects, to make it easier to use for modders?
And, have I listed all the values of interest?

**Comment by KnightMiner** [comment]
We add functions to space damage objects as part of the modloader, you can just do the same thing, right?

That sounds sufficient for what we have currently, source, art, and the type of the space damage.

**Comment by Lemonymous** [comment]
> We add functions to space damage objects as part of the modloader, you can just do the same thing, right?

I didn't see that before, but you are right. I should be able to add functions the same way.

**Comment by Lemonymous** [comment]
I've added the capabilities to get and set `source`, `projectileArt` and SpaceDamage `type` to [memedit_vsproject](https://github.com/itb-community/memedit-vsproject/commit/5aaa89cf2a086133dbdd8fff93284e40eb122a93) and [memedit](https://github.com/itb-community/memedit/commits/master).

I could use some input on how to go about removing the SpaceDamage metadata functions from the mod loader.
I am not sure if we should simply remove them, or change them to report errors, or maybe even something else.

**Comment by Lemonymous** [comment]
When going over skill.lua again, I noticed this code:
```lua
local oldAddGrapple = fx.AddGrapple
SkillEffect.AddGrapple = function(self, source, target, anim, ...)
    local metadataTable = {}
    metadataTable.type = "grapple"
    metadataTable.source = Point(source.x, source.y)
    metadataTable.target = Point(target.x, target.y)
    metadataTable.anim = anim

    oldAddGrapple(self, source, target, anim, ...)
    -- store metadaata in the grapple space damage
    addDamageListMetadata(self.effect, metadataTable, true)
end
```
Seems grapple also stores some metadata that I need to find a substitution for.

**Comment by KnightMiner** [comment]
Probably worth reaching out to karto regarding removal of metadata. With the right getters, you could just have the functions return approximately the same thing by calling memedit functions

**Comment by kartoFlane** [comment]
Storing SpaceDamage metadata in a script has always been a hack, if we can obtain the same information via memedit and store/present it more robustly, then the current implementation of metadata should absolutely be removed

**Comment by Lemonymous** [comment]
The data can now be obtained by memedit 62cf18ad899234f3eccaaf467ddef1a0ad0ff874
Remaining issue:
- Remove SpaceDamage metadata storage in mod loader
