### ISSUE TITLE
Deployment detection system only triggers when the first Mech (Pawn ID 0) has landed, which is incompatible with the randomness of deployment order.

### ISSUE THREAD

**Issue by WolframParadoxica** [itb-community/ITB-ModLoader#199]
This results in the other two mechs being occasionally failed to be detected when they are deployed, resulting in attempts to make deployment effects not working 100% of the time.

**Comment by WolframParadoxica** [comment]
The specific event subscription this is known to occur with is modApi.events.onPawnLanded:subscribe(), further testing remains to be seen.

**Comment by WolframParadoxica** [comment]
Line 211 of deployment.lua

`		local isAllDeployed = true
			and mechs[0].state == STATE_DEPLOYED
			and mechs[1].state == STATE_DEPLOYED
			and mechs[2].state == STATE_DEPLOYED
			and pwn0:IsBusy()`

**Comment by Lemonymous** [comment]
Fixed by #200
