### ISSUE TITLE
Add hooks for Board:AddEffect and Environment:GetAttackEffect

### ISSUE THREAD

**Issue by tos-x** [itb-community/ITB-ModLoader#201]
Skillbuild hooks only work on tables in `_G` that have `GetSkillEffect`; SkillEffects added via other methods would also benefit from hooks or events to allow users to manipulate them.

Consider overriding `Board:AddEffect` (and possibly `Board:DamageSpace`) via [events](https://github.com/itb-community/ITB-ModLoader/wiki/events#onBoardClassInitialized).

Consider adding an environment attack hook that triggers on `GetAttackEffect` similar to how Skillbuild hooks trigger on `GetSkillEffect`.

**Comment by tos-x** [comment]
From Lemonymous: For the board event, if you follow this example, and change the function; replace the logging with something like
`myEvent:dispatch(arg1, arg2, etc)`

You create the event further up with
`local myEvent = Event()`

Then subscribe to the event with
`myEvent:subscribe(someFunctWith3Args)`

**Comment by KnightMiner** [comment]
Isn't skill build hook a modApiExt thing? Might make more sense to add this proposed hook there

**Comment by tos-x** [comment]
Look like the skillEffect returned by `Environment:GetAttackEffect()` gets added via `Board:AddEffect()`, so there's no real need to add hooks for it, unless the same granularity (start and end hooks) is desired.

**Comment by Lemonymous** [comment]
Solved in #205 and release 2.9.2
