### ISSUE TITLE
Vek Move End Hook has an incorrect endLoc

### ISSUE THREAD

**Issue by FloranDev2** [itb-community/ITB-ModLoader#211]
The vek move end hook (https://github.com/itb-community/ITB-ModUtils/blob/master/hooks.md#vekmoveendhook) give an endLoc equal to the startLoc.

I've described the issue in details here: https://discord.com/channels/417639520507527189/1105135399749288077/1105135399749288077

I've noticed that the few frames after the hook, the board is not busy, and once it becomes busy again, the Vek has its position changed, BUT it's not quite the endLoc. Sometimes it is, sometimes not. (I suspect it's the first tile the Vek goes for its path)

**Comment by Lemonymous** [comment]
This issue looks like it should be in [ITB-ModUtils issues](https://github.com/itb-community/ITB-ModUtils/issues)

**Comment by FloranDev2** [comment]
Oh sorry, you're right. I'll create an issue there.
