### ISSUE TITLE
Mod options can't have more than 5 possible values at any given time

### ISSUE THREAD

**Issue by GenericCorporatePilot2005** [itb-community/ITB-ModLoader#218]
if the option for a mod has (for example) 6 values on the init, the mod loader will ignore the 6th value and onwards, just leaving the 5th and previous values

**Comment by NamesAreHard6600** [comment]
Commit aa12c6c

**Comment by GenericCorporatePilot2005** [comment]
nice

**Comment by GenericCorporatePilot2005** [comment]
> Commit [aa12c6c](https://github.com/itb-community/ITB-ModLoader/commit/aa12c6c3c7adfd93f2e29fea4c9065f3496ce812)

thank you :)
